src/Orchard.Web/Modules/Time.OrderLog/Controllers/LiftModelController.cs
using Orchard;
using Orchard.Localization;
using Orchard.Themes;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Time.Data.EntityModels.OrderLog;
using Time.OrderLog.Models;

namespace Time.OrderLog.Controllers
{
    [Authorize]
    [Themed]
    public class LiftModelController : Controller
    {
        public IOrchardServices Services { get; set; }
        public Localizer T { get; set; }
        private OrderLogEntities db;

        public LiftModelController(IOrchardServices services)
        {
            Services = services;
            T = NullLocalizer.Instance;
            db = new OrderLogEntities();
            Setup();
        }

        public LiftModelController(IOrchardServices services, OrderLogEntities _db)
        {
            Services = services;
            T = NullLocalizer.Instance;
            db = _db;
            Setup();
        }

        public void Setup()
        {
            var vm = new MenuViewModel();
            if (Services.Authorizer.Authorize(Permissions.ViewOrders)) vm.ViewOrders = true;
            if (Services.Authorizer.Authorize(Permissions.EditOrders)) vm.EditOrders = true;
            if (Services.Authorizer.Authorize(Permissions.OrderLogReporting)) vm.OrderLogReporting = true;
            ViewBag.Permissions = vm;
        }

        // GET: /LiftModel/
        public ActionResult Index()
        {
            if (!Services.Authorizer.Authorize(Permissions.EditOrders, T("You Do Not Have Permission to Edit")))
                return new HttpUnauthorizedResult();
            return View(db.LiftModels.OrderBy(x => x.LiftModelName));
        }

        
        // GET: /LiftModel/Create
        public ActionResult Create()
        {
            if (!Services.Authorizer.Authorize(Permissions.EditOrders, T("You Do Not Have Permission to Edit")))
                return new HttpUnauthorizedResult();
            return View();
        }

        // POST: /LiftModel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LiftModelName")] LiftModel liftmodel)
        {
            if (!Services.Authorizer.Authorize(Permissions.EditOrders, T("You Do Not Have Permission to Edit")))
                return new HttpUnauthorizedResult();
            var qry = db.LiftModels.FirstOrDefault(x => x.LiftModelName == liftmodel.LiftModelName);

            if (qry != null) ModelState.AddModelError("LiftModelName", "Model Already Exists in Database");

            if (ModelState.IsValid)
            {
                db.LiftModels.Add(liftmodel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(liftmodel);
        }

        // GET: /LiftModel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!Services.Authorizer.Authorize(Permissions.EditOrders, T("You Do Not Have Permission to Edit")))
                return new HttpUnauthorizedResult();
            LiftModel liftmodel = db.LiftModels.Find(id);
            if (liftmodel == null)
            {
                return HttpNotFound();
            }
            return View(liftmodel);
        }

        // POST: /LiftModel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LiftModelId,LiftModelName")] LiftModel liftmodel)
        {
            if (!Services.Authorizer.Authorize(Permissions.EditOrders, T("You Do Not Have Permission to Edit")))
                return new HttpUnauthorizedResult();
            if (ModelState.IsValid)
            {
                db.Entry(liftmodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(liftmodel);
        }

        // GET: /LiftModel/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!Services.Authorizer.Authorize(Permissions.EditOrders, T("You Do Not Have Permission to Edit")))
                return new HttpUnauthorizedResult();
            LiftModel liftmodel = db.LiftModels.Find(id);
            if (liftmodel == null)
            {
                return HttpNotFound();
            }
            return View(liftmodel);
        }

        // POST: /LiftModel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!Services.Authorizer.Authorize(Permissions.EditOrders, T("You Do Not Have Permission to Edit")))
                return new HttpUnauthorizedResult();
            LiftModel liftmodel = db.LiftModels.Find(id);
            db.LiftModels.Remove(liftmodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/Orchard.Web/Modules/Time.OrderLog/Views/LiftModel/Create.cshtml
@model Time.Data.EntityModels.OrderLog.LiftModel

@{
    ViewBag.Title = "Create";
}

@Html.Partial("_Menu", ViewBag.Permissions as Time.OrderLog.Models.MenuViewModel)

<h2>Add New Lift Model</h2>
<hr />


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.LiftModelName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LiftModelName)
                @Html.ValidationMessageFor(model => model.LiftModelName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Orchard.Web/Modules/Time.OrderLog/Views/LiftModel/Delete.cshtml
@model Time.Data.EntityModels.OrderLog.LiftModel

@{
    ViewBag.Title = "Delete";
}

@Html.Partial("_Menu", ViewBag.Permissions as Time.OrderLog.Models.MenuViewModel)

<h2>@ViewBag.Title</h2>
<hr />

<h3>Are you sure you want to delete this?</h3>
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LiftModelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LiftModelName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

src/Orchard.Web/Modules/Time.OrderLog/Views/LiftModel/Edit.cshtml
@model Time.Data.EntityModels.OrderLog.LiftModel

@{
    ViewBag.Title = "Edit Lift Model";
}

@Html.Partial("_Menu", ViewBag.Permissions as Time.OrderLog.Models.MenuViewModel)

<h2>@ViewBag.Title</h2>
<hr />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.LiftModelId)

        <div class="form-group">
            @Html.LabelFor(model => model.LiftModelName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LiftModelName)
                @Html.ValidationMessageFor(model => model.LiftModelName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Orchard.Web/Modules/Time.OrderLog/Views/LiftModel/Index.cshtml
@model IEnumerable<Time.Data.EntityModels.OrderLog.LiftModel>

@{
    ViewBag.Title = "Lift Models";
}

@Html.Partial("_Menu", ViewBag.Permissions as Time.OrderLog.Models.MenuViewModel)

<h2>@ViewBag.Title</h2>
<hr />
<div>
    @Html.ActionLink("Add a Lift Model", "Create", "LiftModel", null, new { @class = "btn btn-primary" })
</div>
<hr />
<table class="table table-striped table-bordered table-condensed">
    <tr class="success">
        <th>
            @Html.DisplayNameFor(model => model.LiftModelName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LiftModelName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.LiftModelId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.LiftModelId })
            </td>
        </tr>
    }

</table>