src/Orchard.Web/Modules/Time.IT/Models/MonitorsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Time.IT.Models
{
    public class MonitorsViewModel
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string MFRName { get; set; }
        public string Model { get; set; }
        public string SerialNo { get; set; }
        public string AssetId { get; set; }
        public string Size { get; set; }
        public string PurchaseDate { get; set; }
        public string PurchasedFrom { get; set; }
        public string PO { get; set; }
        public decimal? Cost { get; set; }
        public string Notes { get; set; }
    }
}

src/Orchard.Web/Modules/Time.IT/Controllers/MonitorController.cs
using Orchard.Themes;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Time.Data.EntityModels.ITInventory;
using Time.IT.Models;

namespace Time.IT.Controllers
{
    [Themed]
    [Authorize]
    public class MonitorController : Controller
    {
        private ITInventoryEntities db = new ITInventoryEntities();

        // GET: Monitor
        public ActionResult Index()
        {
            //var monitors = db.Monitors.OrderBy(x => x.Ref_Manufacturer.Name).ThenBy(x => x.SerialNo).Include(m => m.Ref_Manufacturer).Include(m => m.Ref_MonitorSizes).Include(m => m.User);
            //return View(monitors.ToList());
            return View();
        }

        // Load the data for the Index table
        public ActionResult LoadMonitors()
        {

            List<MonitorsViewModel> model = new List<MonitorsViewModel>();
            //db.Configuration.ProxyCreationEnabled = false;
            var monitors = db.Monitors.OrderBy(x => x.Ref_Manufacturer.Name).ThenBy(x => x.SerialNo).Include(m => m.Ref_Manufacturer).Include(m => m.Ref_MonitorSizes).Include(m => m.User);
            foreach (var item in monitors)
            {
                MonitorsViewModel mvm = new MonitorsViewModel();
                mvm.Id = item.Id;
                mvm.UserName = (item.User != null)? item.User.Name : "";
                mvm.MFRName = item.Ref_Manufacturer.Name;
                mvm.Model = (item.Model == null) ? "Model not found" : item.Model;
                mvm.SerialNo = item.SerialNo;
                mvm.AssetId = item.AssetId;
                mvm.Size = item.Ref_MonitorSizes.Size;
                mvm.PurchaseDate = (item.PurchaseDate != null) ? item.PurchaseDate.Value.ToShortDateString() : "";
                mvm.PO = item.PO;
                mvm.PurchasedFrom = item.PurchasedFrom;
                mvm.Cost = item.Cost;
                mvm.Notes = item.Notes;
                model.Add(mvm);
            }
            return Json(new { data = model }, JsonRequestBehavior.AllowGet);
        }

        // GET: Monitor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monitor monitor = db.Monitors.Find(id);
            if (monitor == null)
            {
                return HttpNotFound();
            }
            return View(monitor);
        }

        // GET: Monitor/Create
        public ActionResult Create()
        {
            GetDropDowns(new Monitor());
            return View();
        }

        // POST: Monitor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "Id")] Monitor monitor)
        {
            if (ModelState.IsValid)
            {
                db.Monitors.Add(monitor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            GetDropDowns(monitor);
            return View(monitor);
        }

        private void GetDropDowns(Monitor monitor)
        {
            ViewBag.ManufacturerId = new SelectList(db.Ref_Manufacturer.OrderBy(x => x.Name), "Id", "Name", monitor.ManufacturerId);
            ViewBag.SizeId = new SelectList(db.Ref_MonitorSizes.OrderBy(x => x.Size), "Id", "Size", monitor.SizeId);
            ViewBag.UserId = new SelectList(db.Users.OrderBy(x => x.Name), "Id", "Name", monitor.UserId);
        }

        // GET: Monitor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monitor monitor = db.Monitors.Find(id);
            if (monitor == null)
            {
                return HttpNotFound();
            }
            GetDropDowns(monitor);
            return View(monitor);
        }

        // POST: Monitor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Monitor monitor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(monitor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            GetDropDowns(monitor);
            return View(monitor);
        }

        // GET: Monitor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monitor monitor = db.Monitors.Find(id);
            if (monitor == null)
            {
                return HttpNotFound();
            }
            return View(monitor);
        }

        // POST: Monitor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Monitor monitor = db.Monitors.Find(id);
            db.Monitors.Remove(monitor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //// The Save action handles both the Create an Edit of Monitor records
        //[HttpGet]
        //public ActionResult Save(int id)
        //{
        //    var monitor = db.Monitors.FirstOrDefault(x => x.Id == id);
        //    if (monitor == null) monitor = new Monitor();
        //    if (id > 0) GetDropDowns(monitor);
        //    else GetDropDowns(new Monitor());
        //    return View(monitor);
        //}
        //// Drop downs for the View
        //private void GetDropDowns(Monitor monitor)
        //{
        //    ViewBag.ManufacturerId = new SelectList(db.Ref_Manufacturer.OrderBy(x => x.Name), "Id", "Name", monitor.ManufacturerId);
        //    ViewBag.SizeId = new SelectList(db.Ref_MonitorSizes.OrderBy(x => x.Size), "Id", "Size", monitor.SizeId);
        //    ViewBag.UserId = new SelectList(db.Users.OrderBy(x => x.Name), "Id", "Name", monitor.UserId);
        //}

        //[HttpPost]// Save POST
        //public ActionResult Save(Monitor mtr)
        //{
        //    bool status = false;
        //    if (ModelState.IsValid)
        //    {
        //        if (mtr.Id > 0)
        //        {
        //            // Edit the Monitor
        //            var monitor = db.Monitors.FirstOrDefault(x => x.Id == mtr.Id);
        //            if (monitor != null)
        //            {
        //                monitor.UserId = mtr.UserId;
        //                monitor.ManufacturerId = mtr.ManufacturerId;
        //                monitor.Model = mtr.Model;
        //                monitor.SerialNo = mtr.SerialNo;
        //                monitor.AssetId = mtr.AssetId;
        //                monitor.SizeId = mtr.SizeId;
        //                monitor.PurchaseDate = mtr.PurchaseDate;
        //                monitor.PurchasedFrom = mtr.PurchasedFrom;
        //                monitor.PO = mtr.PO;
        //                monitor.Cost = mtr.Cost;
        //            }
        //        }
        //        else
        //        {
        //            // Save the Monitor
        //            db.Monitors.Add(mtr);
        //        }
        //        db.SaveChanges();
        //        status = true;
        //    }
        //    return new JsonResult { Data = new { status = status } };
        //}

        //// Delete Monitor
        //[HttpGet]
        //public ActionResult Delete(int id)
        //{
        //    var monitor = db.Monitors.FirstOrDefault(x => x.Id == id);
        //    if (monitor != null)
        //    {
        //        return View(monitor);
        //    }
        //    else
        //    {
        //        return HttpNotFound();
        //    }
        //}
        //// Confirm Delete Monitor
        //[HttpPost]
        //[ActionName("Delete")]
        //public ActionResult DeleteOrder(int id)
        //{
        //    bool status = false;
        //    var monitor = db.Monitors.FirstOrDefault(x => x.Id == id);
        //    if (monitor != null)
        //    {
        //        db.Monitors.Remove(monitor);
        //        db.SaveChanges();
        //        status = true;
        //    }
        //    return new JsonResult { Data = new { status = status } };
        //}

        //// Display Monitor Details
        //[HttpGet]
        //public ActionResult Details(int id)
        //{
        //    var monitor = db.Monitors.FirstOrDefault(x => x.Id == id);
        //    if (monitor != null)
        //    {
        //        return View(monitor);
        //    }
        //    else
        //    {
        //        return HttpNotFound();
        //    }
        //}
    }
}

src/Orchard.Web/Modules/Time.IT/Views/Monitor/Details.cshtml
@model Time.Data.EntityModels.ITInventory.Monitor

@{
    ViewBag.Title = "Monitor Details";
}
<link href="~/Modules/Time.IT/Styles/style.css" rel="stylesheet" />

<h2>@ViewBag.Title</h2>

<div>
    <h4>Monitor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssetId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssetId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchasedFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchasedFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManufacturerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ref_Manufacturer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ref_MonitorSizes.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ref_MonitorSizes.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayWithBreaksFor(model => model.Notes)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/Orchard.Web/Modules/Time.IT/Views/Monitor/Index.cshtml
@{
    ViewBag.Title = "Monitors Index";
    Script.Require("jQuery");
    Script.Include("~/Modules/Time.IT/Scripts/DataTables/jquery.dataTables.js").AtFoot();
    Script.Include("~/Modules/Time.IT/Scripts/DataTables/dataTables.bootstrap.min.js").AtFoot();
    Script.Include("~/Modules/Time.IT/Scripts/DataTables/dataTables.buttons.min.js").AtFoot();
    Script.Include("~/Modules/Time.IT/Scripts/jszip.min.js").AtFoot();
    Script.Include("~/Modules/Time.IT/Scripts/DataTables/buttons.html5.min.js").AtFoot(); 
}
<link href="~/Modules/Time.IT/Styles/buttons.bootstrap.min.css" rel="stylesheet" />
<link href="~/Modules/Time.IT/Styles/font-awesome.css" rel="stylesheet" />
<link href="~/Modules/Time.IT/Styles/customStyle.css" rel="stylesheet" />
<link href="~/Modules/Time.IT/Styles/mobirise.css" rel="stylesheet" />

<h2>@ViewBag.Title</h2>
<div class="row alert alert-info">
    <div class="col-md-2">
        <a class="btn btn-primary" href="Monitor/Create" >Add New Monitor</a>
    </div>
    <div class="col-md-10">
        <p><span class="label label-warning">Note:</span> All columns are sortable. The Search includes all columns, plus the <i>Notes.</i></p>
    </div>
</div>
<div class="row tablecontainer">
    <table id="monitorsTable" class="table table-striped table-hover table-bordered table-condensed">
        <thead>
            <tr class="success">
                <td>@Html.Label("Model")</td>
                <td>@Html.Label("Serial No")</td>
                <td>@Html.Label("Notes")</td>       @*Listed but hidden*@
                <td>@Html.Label("Asset Id")</td>
                <td>@Html.Label("Purchase Date")</td>
                <td>@Html.Label("Purchased From")</td>
                <td>@Html.Label("PO")</td>
                <td>@Html.Label("Cost")</td>
                <td>@Html.Label("MFR Name")</td>
                <td>@Html.Label("Size")</td>
                <td>@Html.Label("User Name")</td>
                <td></td>
                <td></td>
            </tr>
        </thead>
    </table>
</div>

@using (Script.Foot())
{
    <script type="text/javascript">
        $(document).ready(function () {
            var urlLM = '@Url.Action("LoadMonitors", "Monitor")';
            var oTable = $("#monitorsTable").DataTable({
                ajax: {
                    url: urlLM,
                    type: "GET",
                    datatype: "json"
                },
                dom: "<'row'<'col-md-3'l><'col-md-3'B><'col-md-6 text-right'f>><'row'<'col-md-12'tr>><'row'<'col-md-5'i><'col-md-7 text-right'p>>",
                buttons: [{ extend: "excel", text: "Export to Excel", className: "btn btn-primary btn-sm excelButton", filename: 'MonitorsList', }],
                order: [[8, "asc"]],
                stateSave: true,
                displayLength: -1,
                lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]],
                columns: [
                    {
                        data: null, autoWidth: true, render: function (data, type, row) {
                            return '<a href="Monitor/Details/' + row.Id + '">'+ row.Model +'</a>';
                        }
                    },
                    { data: "SerialNo", autoWidth: true },
                    { data: "Notes", autoWidth: true }, // Listed but hidden
                    { data: "AssetId", autoWidth: true },
                    { data: "PurchaseDate", autoWidth: true},
                    { data: "PurchasedFrom", autoWidth: true },
                    { data: "PO", autoWidth: true },
                    { data: "Cost", autoWidth: true, render: $.fn.dataTable.render.number(',', '.', 2, '$')},
                    { data: "MFRName", autoWidth: true },
                    { data: "Size", autoWidth: true },
                    { data: "UserName", autoWidth: true },
                    {
                        data: "Id", width: "20px", sortable: false, render: function (data) {
                            return '<a href="Monitor/Edit/' + data + '"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>';
                        }
                    },
                    {
                        data: "Id", width: "20px", sortable: false, render: function (data) {
                            return '<a href="Monitor/Delete/' + data + '"><i class="fa fa-trash-o" aria-hidden="true"></i></a>';
                        }
                    }
                ]
            })
            // Hiding these columns
            oTable.column(2).visible(false);
        });
    </script>
}

src/Orchard.Web/Modules/Time.IT/Views/Monitor/Save.cshtml

@model Time.Data.EntityModels.ITInventory.Monitor

@if (Model.Id > 0)
{ <h2>Edit Monitor</h2> }
else
{ <h2>Create New Monitor</h2> }

@using (Html.BeginForm("Save", "Monitor", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model != null && Model.Id > 0)
    {
        @Html.HiddenFor(model => model.Id)
    }
    <div class="form-group">
        @Html.Label("User")
        @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" }, optionLabel: "-- Select --")
        @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
    </div>

        <div class="form-group">
            @Html.Label("Manufacturer")
            @Html.DropDownList("ManufacturerId", null, htmlAttributes: new { @class = "form-control" }, optionLabel: "-- Select --")
            @Html.ValidationMessageFor(model => model.ManufacturerId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model)
            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialNo)
            @Html.EditorFor(model => model.SerialNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SerialNo, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssetId)
            @Html.EditorFor(model => model.AssetId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AssetId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Size")
            @Html.DropDownList("SizeId", null, htmlAttributes: new { @class = "form-control" }, optionLabel: "-- Select --")
            @Html.ValidationMessageFor(model => model.SizeId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseDate)
            @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchasedFrom)
            @Html.EditorFor(model => model.PurchasedFrom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PurchasedFrom, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PO)
            @Html.EditorFor(model => model.PO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PO, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost)
            @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
        </div>

        <div>
            <input class="btn btn-primary" type="submit" value="Save" />
        </div>

}


src/Orchard.Web/Modules/Time.IT/Views/Monitor/_Index.cshtml
@{
    ViewBag.Title = "Monitor Index";
    //Style.Require("~/Modules/Time.IT/Content/DataTables/css/dataTables.bootstrap.min.css").AtHead();
    //Style.Require("~/Modules/Time.IT/Content/themes/base/jquery-ui.min.css").AtHead();
    Script.Require("jQuery");
    Script.Include("~/Modules/Time.IT/Scripts/jquery-ui-1.12.1.min.js").AtFoot();
    Script.Include("~/Modules/Time.IT/Scripts/DataTables/jquery.dataTables.min.js").AtFoot();
    Script.Include("~/Modules/Time.IT/Scripts/DataTables/dataTables.bootstrap.min.js").AtFoot();
}

<h2>@ViewBag.Title</h2>

<div class=" tablecontainer">
    <a class="popup btn btn-primary" href="/DataTable/Save/0" style="margin-bottom:20px; margin-top:20px;">Add New Monitor</a>
    <table id="myTable" class="table table-striped table-hover">
        <thead>
            <tr class="success">
                <td>Model</td>
                <td>SerialNo</td>
                <td>AssetId</td>
                <td>PurchaseDate</td>
                <td>PurchasedFrom</td>
                <td>PO</td>
                <td>Cost</td>
                <td>M Name</td>
                <td>Size</td>
                <td>U Name</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </thead>
    </table>
</div>

@using (Script.Foot())
{
    <script type="text/javascript">
        $(document).ready(function () {
            var url = '@Url.Action("LoadMonitors", "Monitor")';
            var oTable = $("#myTable").DataTable({
                "ajax": {
                    "url": url,//"~/Modules/Time.IT/Monitor/LoadMonitors",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "Model", "autoWidth": true },
                    { "data": "SerialNo", "autoWidth": true },
                    { "data": "AssetId", "autoWidth": true },
                    {
                        "data": "PurchaseDate", "autoWidth": true, "render": function () {
                            return (dtConvFromJSON(data));
                        }
                    },
                    { "data": "PurchasedFrom", "autoWidth": true },
                    { "data": "PO", "autoWidth": true },
                    { "data": "Cost", "autoWidth": true },
                    { "data": "ManufacturerId", "autoWidth": true },
                    { "data": "SizeId", "autoWidth": true },
                    {
                        "data": null, "autoWidth": true, "render": function (data, type, row) {
                            return row.User.Name
                        }
                    },
                    {
                        "data": "Id", "width": "20px", "sortable": false, "render": function (data) {
                            return '<a class="popup" href="/Monitor/Save/' + data + '"><img src="~/Media/Default/Page/EditIcon.png" width="20" height="20"/></a>';
                        }
                    },
                    {
                        "data": "Id", "width": "20px", "sortable": false, "render": function (data) {
                            return '<a class="popup" href="/Monitor/Details/' + data + '"><img src="~/Media/Default/Page/DetailIcon.png"  width="20" height="20"/></a>';
                        }
                    },
                    {
                        "data": "Id", "width": "20px", "sortable": false, "render": function (data) {
                            return '<a class="popup" href="/Monitor/Delete/' + data + '"><img src="~/Media/Default/Page/DeleteIcon.png" width="20" height="20"/></a>';
                        }
                    }
                ]
            })
            $('.tablecontainer').on('click', 'a.popup', function (e) {
                e.preventDefault();
                OpenPopup($(this).attr('href'));
            })
            function OpenPopup(pageUrl) {
                var $pageContent = $('<div/>');
                $pageContent.load(pageUrl, function () {
                    $('#popupForm', $pageContent).removeData('validator');
                    $('#popupForm', $pageContent).removeData('unobtrusiveValidation');
                    $.validator.unobtrusive.parse('form');

                });

                $dialog = $('<div class="popupWindow" style="overflow:auto"></div>')
                            .html($pageContent)
                            .dialog({
                                draggable: false,
                                autoOpen: false,
                                resizable: false,
                                model: true,
                                title: 'Popup Dialog',
                                height: 550,
                                width: 600,
                                close: function () {
                                    $dialog.dialog('destroy').remove();
                                }
                            })

                $('.popupWindow').on('submit', '#popupForm', function (e) {
                    var url = $('#popupForm')[0].action;
                    $.ajax({
                        type: "POST",
                        url: url,
                        data: $('#popupForm').serialize(),
                        success: function (data) {
                            if (data.status) {
                                $dialog.dialog('close');
                                oTable.ajax.reload();
                            }
                        }
                    })

                    e.preventDefault();
                })
                $dialog.dialog('open');
            }

            function dtConvFromJSON(data) {
                if (data == null) return '1/1/1950';
                var r = /\/Date\(([0-9]+)\)\//gi
                var matches = data.match(r);
                if (matches == null) return '1/1/1950';
                var result = matches.toString().substring(6, 19);
                var epochMilliseconds = result.replace(/^\/Date\(([0-9]+)([+-][0-9]{4})?\)\/$/, '$1');
                var b = new Date(parseInt(epochMilliseconds));
                var c = new Date(b.toString());
                var curr_date = c.getDate();
                var curr_month = c.getMonth() + 1;
                var curr_year = c.getFullYear();
                var curr_h = c.getHours();
                var curr_m = c.getMinutes();
                var curr_s = c.getSeconds();
                var curr_offset = c.getTimezoneOffset() / 60
                var d = curr_month.toString() + '/' + curr_date + '/' + curr_year;// + " " + curr_h + ':' + curr_m + ':' + curr_s;
                return d;
            }
        });
    </script>
}
@*@model IEnumerable<Time.Data.EntityModels.ITInventory.Monitor>

    @{
        ViewBag.Title = "Monitor Index";
    }

    <h2>@ViewBag.Title</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    <hr />

    <table class="table table-striped table-bordered table-condensed table-hover">
        <tr class="success">
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SerialNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssetId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PurchaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PurchasedFrom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ref_Manufacturer.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ref_MonitorSizes.Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User.Name)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SerialNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AssetId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PurchaseDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PurchasedFrom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ref_Manufacturer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ref_MonitorSizes.Size)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>*@