src/Orchard.Web/Modules/Time.Configurator/Models/ComplexLinkMatrixViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Time.Data.EntityModels.Configurator;

namespace Time.Configurator.Models
{
    public class ComplexLinkMatrixViewModel
    {
        public ComplexStructure complexStructure { get; set; }
        public IEnumerable<Lookup> Lookups { get; set; }
        public IEnumerable<IEnumerable<ComplexLink>> ComplexLinks { get; set; }
    }
}

src/Orchard.Web/Modules/Time.Configurator/Controllers/ComplexStructuresController.cs
using Orchard;
using Orchard.Localization;
using Orchard.Themes;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Time.Configurator.Models;
using Time.Data.EntityModels.Configurator;

namespace Time.Configurator.Controllers
{
    [Themed]
    [Authorize]
    public class ComplexStructuresController : Controller
    {
        private ConfiguratorEntities db = new ConfiguratorEntities();

        public IOrchardServices Services { get; set; }
        public Localizer T { get; set; }

        public ComplexStructuresController(IOrchardServices services)
        {
            Services = services;
            db = new ConfiguratorEntities();
        }

        public ComplexStructuresController(IOrchardServices services, ConfiguratorEntities _db)
        {
            Services = services;
            db = _db;
        }

        // GET: ComplexStructures
        public ActionResult Index(string ConfigNames, string ConfigData)
        {
            ViewBag.ConfigNames = new SelectList(db.ConfiguratorNames.OrderBy(x => x.ConfigName), "ConfigName", "ConfigName");
            ViewBag.ConfigData = new SelectList(db.ComplexStructures.Select(x => x.ConfigData).Distinct());

            if (String.IsNullOrEmpty(ConfigNames) && String.IsNullOrEmpty(ConfigData))
            {
                return View();
            }
            else
            {
                var complexStructures = db.ComplexStructures.AsQueryable();
                if (!String.IsNullOrEmpty(ConfigNames)) complexStructures = complexStructures.Where(x => x.ConfigName == ConfigNames);
                if (!String.IsNullOrEmpty(ConfigData)) complexStructures = complexStructures.Where(x => x.ConfigData == ConfigData);

                return View(complexStructures.OrderBy(x => x.ConfigName).ThenBy(x => x.ConfigData).ToList());
            }
        }

        // GET: ComplexStructures/Details/5
        public ActionResult Details(int? id, string Search)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ComplexStructure complexStructure = db.ComplexStructures.Find(id);
            if (complexStructure == null)
            {
                return HttpNotFound();
            }

            ViewBag.Notes = db.ComplexStructures.Where(x => x.ConfigName == complexStructure.ConfigName && x.ConfigData == complexStructure.ConfigData).ToList();
            ViewBag.Search = Search;
            return View(complexStructure);
        }

        //public ActionResult ComplexLinks(int? id)
        //{
        //    // id = ComplexStructure.Id
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }

        //    var complexLinks = db.ComplexLinks.Where(x => x.ComplexDataId == id);

        //    if (complexLinks == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    return View();
        //}

        public ActionResult _LookupMatrix(int id)
        {
            //var lookups = new List<Lookup>();
            var complexStructure = db.ComplexStructures.Find(id);
            var lookups = db.Lookups.Where(x => x.ConfigName == complexStructure.ConfigName && x.ConfigData == complexStructure.ConfigData).OrderBy(x => x.Id);
            //foreach (var item in cxLookups)
            //{
            //    foreach (var link in item.ComplexLinks)
            //    {
            //        lookups.Add(link.Lookup);
            //    }
            //}
            return PartialView(lookups);
        }

        public ActionResult _ComplexLinkMatrix(int id, string Search)
        {
            // id = ComplexStructure.Id
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}

            var complexStructure = db.ComplexStructures.Find(id);

            var cbArray = BuildCheckBoxArray(complexStructure, Search);

            var lookups = db.Lookups.Where(x => x.ConfigName == complexStructure.ConfigName && x.ConfigData == complexStructure.ConfigData).OrderBy(x => x.Id);
            ComplexLinkMatrixViewModel vm = new ComplexLinkMatrixViewModel
            {
                ComplexLinks = cbArray,
                complexStructure = complexStructure,
                Lookups = lookups
            };

            return PartialView(vm);
        }

        private List<List<ComplexLink>> BuildCheckBoxArray(ComplexStructure complexStructure, string Search)
        {
            var list = new List<List<ComplexLink>>();
            var details = db.ComplexLookups
                .Include(x => x.ComplexLinks)
                .Where(x => x.ConfigName == complexStructure.ConfigName && x.ConfigData == complexStructure.ConfigData);
            if (!string.IsNullOrEmpty(Search))
            {
                foreach (var item in Search.Split(' '))
                {
                    details = details.Where(x => x.LookupData.Contains(item));
                }
            }

            foreach (var detail in details.OrderBy(x => x.Id))
            {
                var innerList = new List<ComplexLink>();
                foreach (var source in detail.ComplexLinks.OrderBy(x => x.ComplexDataId))
                {
                    innerList.Add(source);
                }
                list.Add(innerList);
            }

            return list;
        }

        [HttpGet]
        public ActionResult EditComplexLinkMatrix(int id, string Search)
        {
            var complexStructure = db.ComplexStructures.Find(id);

            var cbArray = BuildCheckBoxArray(complexStructure, Search);

            var lookups = db.Lookups.Where(x => x.ConfigName == complexStructure.ConfigName && x.ConfigData == complexStructure.ConfigData)
                .OrderBy(x => x.Id);
            ComplexLinkMatrixViewModel vm = new ComplexLinkMatrixViewModel
            {
                ComplexLinks = cbArray,
                complexStructure = complexStructure,
                Lookups = lookups
            };
            ViewBag.Notes = db.ComplexStructures.Where(x => x.ConfigName == complexStructure.ConfigName && x.ConfigData == complexStructure.ConfigData).ToList();
            ViewBag.Search = Search;

            return View(vm);
        }

        [HttpPost]
        public ActionResult EditComplexLinkMatrix(List<string> Matrix, int id, string Search)
        {
            //if (Matrix != null)
            //{
            // removed null check, as I need to remove them all if I want to delete the linkages
            SaveComplexLinkMatrix(id, Matrix, Search);
            //}

            return RedirectToAction("Details", new { id = id, Search = Search });
        }

        private void SaveComplexLinkMatrix(int id, List<string> matrix, string Search)
        {
            var cxStructure = db.ComplexStructures.Find(id);
            var cxLookups = db.ComplexLookups.Where(x => x.ConfigName == cxStructure.ConfigName && x.ConfigData == cxStructure.ConfigData);

            if (!string.IsNullOrEmpty(Search))
            {
                foreach (var item in Search.Split(' '))
                {
                    cxLookups = cxLookups.Where(x => x.LookupData.Contains(item));
                }
            }

            foreach (var lookup in cxLookups.OrderBy(x => x.Id))
            {
                foreach (var source in lookup.ComplexLinks.OrderBy(x => x.LookupId))
                {
                    string exists = String.Format("{0}, {1}", source.ComplexDataId, source.LookupId);
                    if (matrix != null && matrix.Contains(exists))
                    {
                        source.Available = true;
                    }
                    else
                    {
                        source.Available = false;
                    }
                }
            }

            db.SaveChanges();
        }

        // GET: ComplexStructures/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ComplexStructures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "Id")] ComplexStructure complexStructure)
        {
            if (ModelState.IsValid)
            {
                db.ComplexStructures.Add(complexStructure);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(complexStructure);
        }

        // GET: ComplexStructures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ComplexStructure complexStructure = db.ComplexStructures.Find(id);
            if (complexStructure == null)
            {
                return HttpNotFound();
            }
            return View(complexStructure);
        }

        // POST: ComplexStructures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ComplexStructure complexStructure)
        {

src/Orchard.Web/Modules/Time.Configurator/Controllers/ConfiguratorController.cs
using Orchard;
using Orchard.Localization;
using Orchard.Themes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Time.Data.Models.MessageQueue;

namespace Time.Configurator.Controllers
{
    [Themed]
    public class ConfiguratorController : Controller
    {
        private string ErrorMessage { get; set; }
        public IOrchardServices Services { get; set; }
        public Localizer T { get; set; }

        public ConfiguratorController(IOrchardServices services)
        {
            Services = services;
        }

        // GET: Configurator
        public ActionResult Index()
        {
            if (!Services.Authorizer.Authorize(Permissions.ConfiguratorAdmin, T("You Do Not Have Permission to View this Page")))
                return new HttpUnauthorizedResult();
            return View();
        }

        public ActionResult BuildComplexlookups()
        {
            var command = new EmptyMessage();
            var success = MSMQ.SendQueueMessage(command, MessageType.BuildComplexLookups);
            if (!string.IsNullOrEmpty(ErrorMessage)) ViewBag.ErrorMessage = ErrorMessage;

            ViewBag.Title = "Build Complex Lookup";
            if (success)
            {
                ViewBag.Message = "Build Complex Lookup Message Queued.  It should be sent within the next few moments.";
            }
            else
            {
                ViewBag.Message = "Error queuing/sending the Build Complex Lookup Message. Please try later, or get with IT support to troubleshoot the issue.";
            }

            return View("MessageResult");
        }

        public ActionResult BuildConfigOptions()
        {
            var command = new EmptyMessage();
            var success = MSMQ.SendQueueMessage(command, MessageType.BuildConfigOptions);
            if (!string.IsNullOrEmpty(ErrorMessage)) ViewBag.ErrorMessage = ErrorMessage;

            ViewBag.Title = "Build Config Options";
            if (success)
            {
                ViewBag.Message = "Build Config Options Message Queued.  It should be sent within the next few moments.";
            }
            else
            {
                ViewBag.Message = "Error queuing/sending the Build Config Options Message. Please try later, or get with IT support to troubleshoot the issue.";
            }

            return View("MessageResult");
        }
    }
}

src/Orchard.Web/Modules/Time.Configurator/Views/ComplexStructures/Create.cshtml
@model Time.Data.EntityModels.Configurator.ComplexStructure

@{
    ViewBag.Title = "Create Complex Structure";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Complex Structure</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ConfigName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfigName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfigName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfigData, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfigData, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfigData, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sequence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sequence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sequence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LookupData, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LookupData, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LookupData, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LookupSeq, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LookupSeq, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LookupSeq, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Orchard.Web/Modules/Time.Configurator/Views/ComplexStructures/Delete.cshtml
@model Time.Data.EntityModels.Configurator.ComplexStructure

@{
    ViewBag.Title = "Delete Complex Structure";
}

<link href="~/Modules/Time.IT/Styles/style.css" rel="stylesheet" />

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Complex Structure</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ConfigName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfigName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConfigData)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfigData)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sequence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sequence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LookupData)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LookupData)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LookupSeq)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LookupSeq)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index", new { ConfigNames = Model.ConfigName, ConfigData = Model.ConfigData })
        </div>
    }
</div>

src/Orchard.Web/Modules/Time.Configurator/Views/ComplexStructures/Details.cshtml
@model Time.Data.EntityModels.Configurator.ComplexStructure

@{
    ViewBag.Title = "Complex Structure Details";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Complex Structure</h4>
    <hr />
    <div class="alert alert-info">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ConfigName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConfigName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ConfigData)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConfigData)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sequence)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sequence)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LookupData)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LookupData)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LookupSeq)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LookupSeq)
            </dd>
        </dl>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id}) |
    @Html.ActionLink("Back to List", "Index", new { ConfigNames = Model.ConfigName, ConfigData = Model.ConfigData })
</p>

@using (Html.BeginForm(new { Search = ViewBag.Search }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <hr />
    <div class="row">
        <div class="col-md-5">
            <div class="input-group">
                @Html.TextBox("Search", null, htmlAttributes: new { @placeholder = "Search..." })
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Go!</button>
                </span>
            </div>
        </div>
    </div>
    <hr />
}

@Html.Action("_LookupMatrix", new { id = Model.Id })

@Html.Partial("_CriteriaDescriptions")

@Html.Action("_ComplexLinkMatrix", new { id = Model.Id, Search = ViewBag.Search })

src/Orchard.Web/Modules/Time.Configurator/Views/ComplexStructures/Edit.cshtml
@model Time.Data.EntityModels.Configurator.ComplexStructure

@{
    ViewBag.Title = "Edit Complex Structures";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Complex Structure</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ConfigName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfigName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfigName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfigData, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfigData, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfigData, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sequence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sequence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sequence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LookupData, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LookupData, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LookupData, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LookupSeq, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LookupSeq, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LookupSeq, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { ConfigNames = Model.ConfigName, ConfigData = Model.ConfigData })
</div>

src/Orchard.Web/Modules/Time.Configurator/Views/ComplexStructures/EditComplexLinkMatrix.cshtml
@model Time.Configurator.Models.ComplexLinkMatrixViewModel

@{
    ViewBag.Title = "Edit Complex Link -> Lookup Data Matrix";
}

<h2>@ViewBag.Title</h2>

@Html.Partial("_LookupMatrix", Model.Lookups)

@using (Html.BeginForm(new { Search = ViewBag.Search }))
{
    @Html.AntiForgeryToken()
    @*@Html.HiddenFor(x => x)*@
    @*@Html.HiddenFor(x => x.OrderHeader.Id)*@
    
    @Html.Partial("_CriteriaDescriptions")
    <br />
    
    <div class="clear"></div>    
    <div class="editor-button2">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>

    @Html.Partial("_EditComplexLinkMatrix", Model)

    <div class="clear"></div>
    <div class="editor-button2">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
}

src/Orchard.Web/Modules/Time.Configurator/Views/ComplexStructures/Index.cshtml
@model IEnumerable<Time.Data.EntityModels.Configurator.ComplexStructure>

@{
    ViewBag.Title = "Complex Structures Index";
}

<h2>@ViewBag.Title</h2>

<div align="right">
    <p>
        @Html.ActionLink("Back to Configurator Index", "Index", "Configurator")
    </p>
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="row">
    @using (Html.BeginForm("Index", "ComplexStructures", FormMethod.Get))
    {

        <div class="col-md-3">@Html.DropDownList("ConfigNames", optionLabel: "-- Select ConfigName --")</div>
        <div class="col-md-3">@Html.DropDownList("ConfigData", optionLabel: "-- Select ConfigData --")</div>
        <div class="col-md-2"><input type="submit" value="Search" class="btn btn-primary" /></div>

    }
    <div class="col-md-4">@Html.TextBox("detailsSearch", null, htmlAttributes: new { @placeholder = "Enter alternate value for Details view..." })</div>
</div>

<br />

<table class="table table-striped table-bordered table-condensed table-hover">
    <tr class="success">
        <th>
            @Html.DisplayNameFor(model => model.ConfigName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConfigData)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sequence)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LookupData)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LookupSeq)
        </th>
        <th></th>
    </tr>

    @if (Model == null || Model.Count() == 0)
    {
        <tr>
            <td colspan="7">
                No rows match search criteria
            </td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ConfigName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConfigData)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sequence)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LookupData)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LookupSeq)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                    <a href="#" class="DetailsLink">Details</a> |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    }
</table>



<div align="right">
    <p>
        @Html.ActionLink("Back to Configurator Index", "Index", "Configurator")
    </p>
</div>

@using (Script.Foot())
{
    <script type="text/javascript">
        var model;
        var altSearch;
        var url;
        $(".DetailsLink").click(function () {
            getValues();
            window.open(url);
        });

        function getValues(){
            model = @Html.Raw(Json.Encode(Model));
            altSearch = $("#detailsSearch").val();
            url = "ComplexStructures/Details/" + model[0].Id + "?Search=" + altSearch;
        };
    </script>
}

src/Orchard.Web/Modules/Time.Configurator/Views/ComplexStructures/_ComplexLinkMatrix.cshtml
@using Time.Data.EntityModels.Configurator
@model Time.Configurator.Models.ComplexLinkMatrixViewModel

<h2>
    Complex Lookups -> Lookup Data Matrix
</h2>

@Html.ActionLink("Edit Matrix", "EditComplexLinkMatrix", new { id = Model.complexStructure.Id, Search = ViewBag.Search })

<table class="table table-striped table-bordered table-condensed table-hover">
    <tr class="success">
        <th>&nbsp;</th>
        @foreach (var lookup in Model.Lookups)
        {
            <th>
                @lookup.Id
            </th>
        }
    </tr>
    @if (Model != null)
    {
        if (Model.ComplexLinks != null)
        {
            foreach (var item in Model.ComplexLinks)
            {
                <tr class="success">
                    @if (item.Count() > 0)
                    {
                        <td>
                            @item.FirstOrDefault().ComplexLookup.LookupData
                        </td>
                    }
                    @foreach (var linkitem in item)
                    {
                        <td>
                            @Html.DisplayFor(x => linkitem.Available)
                            @*<input type="checkbox" name="Matrix" checked="@linkitem.Available" value="@linkitem.ComplexDataId, @linkitem.LookupId" />*@
                        </td>
                    }
                </tr>
            }
        }
    }
</table>

src/Orchard.Web/Modules/Time.Configurator/Views/ComplexStructures/_CriteriaDescriptions.cshtml
@*@model Time.Data.EntityModels.Configurator.ComplexStructure*@

<div class="alert alert-info">
    <h4 class="text-info">Criteria Descriptions:</h4>

    @{ int count = 1; }
    @if (ViewBag.Notes != null)
    {
        foreach (var item in ViewBag.Notes as IEnumerable<Time.Data.EntityModels.Configurator.ComplexStructure>)
        {

            <div>
                <b>Criteria @(count) :</b>&nbsp;&nbsp;&nbsp;@item.Notes
            </div>

            count++;
        }
    }
</div>