src/Orchard.Web/Modules/Time.Install/Controllers/OptionGroupsController.cs
using Orchard;
using Orchard.Localization;
using Orchard.Themes;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Time.Data.EntityModels.Install;

namespace Time.Install.Controllers
{
    [Themed]
    [Authorize]
    public class OptionGroupsController : Controller
    {
        private string ErrorMessage { get; set; }
        public IOrchardServices Services { get; set; }
        public Localizer T { get; set; }

        public OptionGroupsController(IOrchardServices services)
        {
            Services = services;
        }

        private VSWQuotesEntities db = new VSWQuotesEntities();

        // GET: OptionGroups
        public ActionResult Index()
        {
            return View(db.OptionGroups.ToList());
        }

        // GET: OptionGroups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OptionGroup optionGroup = db.OptionGroups.Find(id);
            if (optionGroup == null)
            {
                return HttpNotFound();
            }
            return View(optionGroup);
        }

        // GET: OptionGroups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OptionGroups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "Id")] OptionGroup optionGroup)
        {
            if (ModelState.IsValid)
            {
                db.OptionGroups.Add(optionGroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(optionGroup);
        }

        // GET: OptionGroups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OptionGroup optionGroup = db.OptionGroups.Find(id);
            if (optionGroup == null)
            {
                return HttpNotFound();
            }
            return View(optionGroup);
        }

        // POST: OptionGroups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OptionGroup optionGroup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(optionGroup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(optionGroup);
        }

        // GET: OptionGroups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OptionGroup optionGroup = db.OptionGroups.Find(id);
            if (optionGroup == null)
            {
                return HttpNotFound();
            }
            return View(optionGroup);
        }

        // POST: OptionGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OptionGroup optionGroup = db.OptionGroups.Find(id);
            db.OptionGroups.Remove(optionGroup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/Orchard.Web/Modules/Time.Install/Views/OptionGroups/Create.cshtml
@model Time.Data.EntityModels.Install.OptionGroup

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div align="right">
    @Html.ActionLink("Back to Main Menu", "Index", "Home")
</div>
<hr />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="container-fluid bg-info" style="border-radius: 5px;">
        <div class="row">
            <div class="col-md-12">
                <div class="form-horizontal">
                    <h4>Option Group</h4>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Orchard.Web/Modules/Time.Install/Views/OptionGroups/Delete.cshtml
@model Time.Data.EntityModels.Install.OptionGroup

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<div align="right">
    @Html.ActionLink("Back to Main Menu", "Index", "Home")
</div>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Option Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

src/Orchard.Web/Modules/Time.Install/Views/OptionGroups/Details.cshtml
@model Time.Data.EntityModels.Install.OptionGroup

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div align="right">
    @Html.ActionLink("Back to Main Menu", "Index", "Home")
</div>

<div>
    <h4>Option Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/Orchard.Web/Modules/Time.Install/Views/OptionGroups/Edit.cshtml
@model Time.Data.EntityModels.Install.OptionGroup

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div align="right">
    @Html.ActionLink("Back to Main Menu", "Index", "Home")
</div>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid bg-info" style="border-radius: 5px;">
        <div class="row">
            <div class="col-md-12">
                <div class="form-horizontal">
                    <h4>Option Group</h4>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Orchard.Web/Modules/Time.Install/Views/OptionGroups/Index.cshtml
@model IEnumerable<Time.Data.EntityModels.Install.OptionGroup>

@{
    ViewBag.Title = "VSW Option Group Index";
}

<link href="~/Modules/Time.IT/Styles/customStyle.css" rel="stylesheet" />

<h2>@ViewBag.Title</h2>

<div align="right">
    @Html.ActionLink("Back to Main Menu", "Index", "Home")
</div>

<div class="alert alert-info">
    <h4>The information in these pages includes:</h4>
    <p><span class="label label-primary">1.</span> VSW Option Groups.</p>
    <p><span class="label label-success">Tip:</span> Click the button <span class="label label-primary">Show Pictures</span> to display what sections of the previously used documents this page is related to.</p>
</div>
<a id="showInfo" href="#cfgsAndLifts" data-toggle="collapse" class="btn btn-primary btn-xs">Show Pictures</a>
<div id="cfgsAndLifts" class="collapse">
    <div style="display:block; height:300px; overflow:scroll;">
        @Html.Action("MoreInfo", "Home", new { documentSection = "vswOptionGroup" })
    </div>
</div>
<hr />
<div>
    <a style="margin-bottom:5px;" class="btn btn-primary btn-xs" href="@Url.Action("Create", "OptionGroups")">Create New VSW Group</a>
</div>
<table class="table table-striped table-bordered table-hover table-responsive">
    <tr class="success">
        <th class="col-md-11">
            @Html.DisplayNameFor(model => model.GroupName)
        </th>
        <th></th>
        @*<th></th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GroupName)
            </td>
            <td>
                <a href="@Url.Action("Edit", "OptionGroups", new { id = item.Id })"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
            </td>
            @*<td>
                <a href="@Url.Action("Details", "OptionGroups", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true"></i></a>
            </td>*@
            <td>
                <a href="@Url.Action("Delete", "OptionGroups", new { id = item.Id })"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
            </td>
        </tr>
    }

</table>